package views;

import controllers.AnggotaController;
import controllers.InventarisController;
import controllers.KeuanganController;
import controllers.PeminjamanController;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import models.Anggota;
import models.Inventaris;
import models.Keuangan;
import models.KeyValue;
import models.Peminjaman;

/**
 *
 * @author Nazwa Aditya Daniswara
 */
public class PeminjamanView extends javax.swing.JFrame {

    private int id_peminjaman = -1;
    private HashMap<String, Integer> barangMap = new HashMap<>();
    private HashMap<String, Integer> peminjamMap = new HashMap<>();

    /**
     * Creates new form AnggotaView
     */
    public PeminjamanView() {
        initComponents();
        showDataTable();
        setTanggalHariIni();
        loadBarangToComboBox();
        loadPeminjamToComboBox();
    }

    private void loadBarangToComboBox() {
        InventarisController inventarisController = new InventarisController();
        List<Inventaris> listBarang = inventarisController.getAllBarang();

        cbBarang.removeAllItems(); // Kosongkan terlebih dahulu
        barangMap.clear(); // Bersihkan `HashMap` barang

        for (Inventaris barang : listBarang) {
            String namaBarang = barang.getNamaBarang();
            int idBarang = barang.getIdBarang();

            cbBarang.addItem(namaBarang); // Tambahkan nama barang ke ComboBox
            barangMap.put(namaBarang, idBarang); // Simpan relasi nama dan ID di HashMap
        }
    }

    private void loadPeminjamToComboBox() {
        AnggotaController anggotaController = new AnggotaController();
        List<Anggota> listAnggota = anggotaController.getAllAnggota();

        cbAnggota.removeAllItems(); // Kosongkan terlebih dahulu
        peminjamMap.clear(); // Bersihkan `HashMap` peminjam

        for (Anggota anggota : listAnggota) {
            String namaAnggota = anggota.getNama();
            int idAnggota = anggota.getIdAnggota();

            cbAnggota.addItem(namaAnggota); // Tambahkan nama anggota ke ComboBox
            peminjamMap.put(namaAnggota, idAnggota); // Simpan relasi nama dan ID di HashMap
        }
    }

    private void setTanggalHariIni() {
        // Dapatkan tanggal hari ini
        LocalDate today = LocalDate.now();

        // Tentukan format tanggal
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");

        // Format tanggal sebagai string
        String formattedDate = today.format(formatter);

        // Setel tanggal ke field TfTanggal
        TfTglPeminjaman.setText(formattedDate);
        TfTglPengembalian.setText(formattedDate);
    }

    private void showDataTable() {
        // Membuat instance dari PeminjamanController
        PeminjamanController peminjamanController = new PeminjamanController();

        // Mendapatkan daftar semua peminjaman
        List<Peminjaman> listPeminjaman = peminjamanController.getAllPeminjaman();

        // Nama kolom tabel
        String[] columnNames = {"ID", "Nama Barang", "Nama Peminjam", "NIM", "Tanggal Pinjam", "Tanggal Kembali"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

        // Mengisi data ke model tabel
        for (Peminjaman peminjaman : listPeminjaman) {
            Object[] rowData = {
                peminjaman.getIdPeminjaman(),
                peminjaman.getNamaBarang(),
                peminjaman.getNamaAnggota(),
                peminjaman.getNim(),
                peminjaman.getTanggalPeminjaman(),
                peminjaman.getTanggalPengembalian()
            };
            tableModel.addRow(rowData);
        }

        // Menetapkan model ke tabel
        tbPeminjaman.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        dateChooserDialog2 = new datechooser.beans.DateChooserDialog();
        Header1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPeminjaman = new javax.swing.JTable();
        jButtonPdf = new javax.swing.JButton();
        jButtonCsv = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Barang = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonBack = new javax.swing.JButton();
        TfTglPengembalian = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cbAnggota = new javax.swing.JComboBox<>();
        cbBarang = new javax.swing.JComboBox<>();
        TfTglPeminjaman = new javax.swing.JTextField();
        jButtonTambah = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        Footer = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/public/img/kbmsy.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("KBMSY MANAGER");

        javax.swing.GroupLayout Header1Layout = new javax.swing.GroupLayout(Header1);
        Header1.setLayout(Header1Layout);
        Header1Layout.setHorizontalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297)
                .addComponent(jLabel8)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Header1Layout.setVerticalGroup(
            Header1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Header1Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Header1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        tbPeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPeminjamanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbPeminjaman);

        jButtonPdf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonPdf.setText("Export to PDF");
        jButtonPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPdfActionPerformed(evt);
            }
        });

        jButtonCsv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonCsv.setText("Export to Csv");
        jButtonCsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCsvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCsv)
                .addGap(18, 18, 18)
                .addComponent(jButtonPdf)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCsv)
                    .addComponent(jButtonPdf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Peminjam");

        Barang.setText("Nama Barang");

        jLabel3.setText("Tanggal Pinjam");

        jButtonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonBack.setText("KEMBALI");
        jButtonBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jLabel4.setText("Tanggal Kembali");

        cbAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBarangActionPerformed(evt);
            }
        });

        jButtonTambah.setBackground(new java.awt.Color(102, 255, 0));
        jButtonTambah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonTambah.setText("Tambah");
        jButtonTambah.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTambahActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(255, 204, 0));
        jButtonEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonEdit.setText("Edit");
        jButtonEdit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 0, 51));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonDelete.setText("Hapus");
        jButtonDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButtonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TfTglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(TfTglPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(Barang, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(cbAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonBack)
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Barang)
                    .addComponent(cbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TfTglPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TfTglPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTambah)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonDelete))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        Footer.setBackground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Created By: Nazwa Aditya Daniswara (222212788/29)");

        javax.swing.GroupLayout FooterLayout = new javax.swing.GroupLayout(Footer);
        Footer.setLayout(FooterLayout);
        FooterLayout.setHorizontalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(426, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(350, 350, 350))
        );
        FooterLayout.setVerticalGroup(
            FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FooterLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(Header1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetField() {
        setTanggalHariIni();
        id_peminjaman = -1;
    }

    private void jButtonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTambahActionPerformed
        try {
            // Ambil data dari form
            String tanggalPinjamStr = TfTglPeminjaman.getText();
            String tanggalKembaliStr = TfTglPengembalian.getText();

            // Ambil barang dan anggota yang dipilih dari ComboBox
            String namaBarang = (String) cbBarang.getSelectedItem();
            String namaAnggota = (String) cbAnggota.getSelectedItem();

            // Membuat instance dari PeminjamanController
            PeminjamanController peminjamanController = new PeminjamanController();

            // Validasi input menggunakan controller
            peminjamanController.validatePeminjamanData(tanggalPinjamStr, tanggalKembaliStr);

            // Konversi tanggal ke java.sql.Date
            java.sql.Date tanggalPinjam = java.sql.Date.valueOf(tanggalPinjamStr);
            java.sql.Date tanggalKembali = java.sql.Date.valueOf(tanggalKembaliStr);

            // Ambil ID dari HashMap
            int idBarang = getIdBarang(namaBarang);
            int idAnggota = getIdAnggota(namaAnggota);

            // Buat objek Peminjaman
            Peminjaman peminjaman = new Peminjaman(idAnggota, idBarang, tanggalPinjam, tanggalKembali);

            // Tambahkan peminjaman ke database
            peminjamanController.addPeminjaman(peminjaman);

            // Menampilkan dialog konfirmasi berhasil
            JOptionPane.showMessageDialog(this, "Peminjaman berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Refresh tabel setelah penambahan
            showDataTable();
            resetField();
        } catch (IllegalArgumentException e) {
            // Menampilkan dialog error untuk validasi
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Menampilkan dialog error umum
            JOptionPane.showMessageDialog(this, "Gagal menambahkan peminjaman: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonTambahActionPerformed
    
    private int getIdBarang(String namaBarang) {
        // Implementasikan logika untuk mendapatkan ID dari nama barang
        // Jika Anda menggunakan HashMap, misalnya:
        return barangMap.getOrDefault(namaBarang, -1);
    }

    private int getIdAnggota(String namaAnggota) {
        // Misalkan Anda menggunakan HashMap untuk menyimpan ID anggota
        return peminjamMap.getOrDefault(namaAnggota, -1);
    }
    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        try {
            // Ambil ID peminjaman yang dipilih
            int idPeminjaman = id_peminjaman; // pastikan ini adalah ID yang benar dari peminjaman yang dipilih

            // Ambil data dari form
            String tanggalPinjamStr = TfTglPeminjaman.getText();
            String tanggalKembaliStr = TfTglPengembalian.getText();

            // Ambil barang dan anggota yang dipilih dari ComboBox
            String namaBarang = (String) cbBarang.getSelectedItem();
            String namaAnggota = (String) cbAnggota.getSelectedItem();

            // Membuat instance dari PeminjamanController
            PeminjamanController peminjamanController = new PeminjamanController();

            // Validasi input menggunakan controller
            peminjamanController.validatePeminjamanData(tanggalPinjamStr, tanggalKembaliStr);

            // Konversi string tanggal ke java.sql.Date
            java.sql.Date tanggalPinjam = java.sql.Date.valueOf(tanggalPinjamStr);
            java.sql.Date tanggalKembali = java.sql.Date.valueOf(tanggalKembaliStr);

            // Ambil ID dari HashMap atau metode lain yang Anda gunakan
            int idBarang = getIdBarang(namaBarang);
            int idAnggota = getIdAnggota(namaAnggota);

            // Pastikan ID peminjaman yang valid telah dipilih
            if (idPeminjaman != -1) {
                // Membuat objek Peminjaman dengan konstruktor yang sesuai
                Peminjaman peminjaman = new Peminjaman(idPeminjaman, idAnggota, idBarang, tanggalPinjam, tanggalKembali,
                    namaAnggota, "NIM_PLACEHOLDER", "PRODI_PLACEHOLDER", namaBarang);

                // Memperbarui data peminjaman di database
                peminjamanController.updatePeminjaman(peminjaman);
                JOptionPane.showMessageDialog(this, "Data peminjaman berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

                // Reset field input dan refresh tabel
                resetField();
                showDataTable();
            } else {
                JOptionPane.showMessageDialog(this, "Silahkan pilih data peminjaman yang valid!", "Gagal", JOptionPane.ERROR_MESSAGE);
            }
        } catch (IllegalArgumentException e) {
            // Menampilkan dialog error untuk validasi
            JOptionPane.showMessageDialog(this, e.getMessage(), "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            // Menampilkan dialog error umum
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int idPeminjaman = id_peminjaman; // Ambil ID peminjaman yang dipilih

        if (idPeminjaman != -1) {
            PeminjamanController peminjamanController = new PeminjamanController();

            // Menghapus data peminjaman dari database
            try {
                int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus peminjaman dengan ID: " 
                        + idPeminjaman + "?", "Konfirmasi Penghapusan", JOptionPane.YES_NO_OPTION);
                if (confirm == JOptionPane.YES_OPTION) {
                    peminjamanController.deletePeminjaman(idPeminjaman);
                    JOptionPane.showMessageDialog(this, "Data peminjaman berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    resetField();
                    showDataTable();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data peminjaman terlebih dahulu", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void tbPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPeminjamanMouseClicked
        // Mendapatkan indeks baris yang diklik
        int selectedRow = tbPeminjaman.getSelectedRow();

        // Pastikan ada baris yang dipilih
        if (selectedRow >= 0) {
            // Mendapatkan model tabel untuk mengakses data
            DefaultTableModel model = (DefaultTableModel) tbPeminjaman.getModel();

            // Mengambil data dari baris yang diklik
            String id = model.getValueAt(selectedRow, 0).toString();
            String namaBarang = model.getValueAt(selectedRow, 1).toString();
            String namaPeminjam = model.getValueAt(selectedRow, 2).toString();
            String nim = model.getValueAt(selectedRow, 3).toString();
            String tanggalPinjam = model.getValueAt(selectedRow, 4).toString();
            String tanggalKembali = model.getValueAt(selectedRow, 5).toString();

            // Menetapkan data ke field-field input
            id_peminjaman = Integer.parseInt(id); // Pastikan `id_peminjaman` adalah variabel yang menyimpan ID peminjaman
            cbBarang.setSelectedItem(namaBarang);
            cbAnggota.setSelectedItem(namaPeminjam);
            TfTglPeminjaman.setText(tanggalPinjam);
            TfTglPengembalian.setText(tanggalKembali);
        }
    }//GEN-LAST:event_tbPeminjamanMouseClicked

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
        DashboardView dashboardView = new DashboardView();
        dashboardView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void cbBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbBarangActionPerformed

    private void jButtonPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPdfActionPerformed
        // TODO add your handling code here:
        // Mendapatkan model tabel
        DefaultTableModel tableModel = (DefaultTableModel) tbPeminjaman.getModel();
        
        // Membuat instance controller
        PeminjamanController controller = new PeminjamanController();
        
        // Memanggil metode ekspor PDF
        controller.exportToPdf(tableModel, this);
    }//GEN-LAST:event_jButtonPdfActionPerformed

    private void jButtonCsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCsvActionPerformed
        // TODO add your handling code here:
        // Mendapatkan model tabel
        DefaultTableModel tableModel = (DefaultTableModel) tbPeminjaman.getModel();
        
        // Membuat instance controller
        PeminjamanController controller = new PeminjamanController();
        
        // Memanggil metode ekspor CSV
        controller.exportToCsv(tableModel, this);
    }//GEN-LAST:event_jButtonCsvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeminjamanView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeminjamanView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Barang;
    private javax.swing.JPanel Footer;
    private javax.swing.JPanel Header1;
    private javax.swing.JTextField TfTglPeminjaman;
    private javax.swing.JTextField TfTglPengembalian;
    private javax.swing.JComboBox<String> cbAnggota;
    private javax.swing.JComboBox<String> cbBarang;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private datechooser.beans.DateChooserDialog dateChooserDialog2;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonCsv;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonPdf;
    private javax.swing.JButton jButtonTambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPeminjaman;
    // End of variables declaration//GEN-END:variables
}
